package cent.news.com.newscent.db.graeendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cent.news.com.newscent.news.channel.ChannelDBBean;
import cent.news.com.newscent.news.channel.ChannelDBOne2N;

import cent.news.com.newscent.db.graeendao.ChannelDBBeanDao;
import cent.news.com.newscent.db.graeendao.ChannelDBOne2NDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig channelDBBeanDaoConfig;
    private final DaoConfig channelDBOne2NDaoConfig;

    private final ChannelDBBeanDao channelDBBeanDao;
    private final ChannelDBOne2NDao channelDBOne2NDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        channelDBBeanDaoConfig = daoConfigMap.get(ChannelDBBeanDao.class).clone();
        channelDBBeanDaoConfig.initIdentityScope(type);

        channelDBOne2NDaoConfig = daoConfigMap.get(ChannelDBOne2NDao.class).clone();
        channelDBOne2NDaoConfig.initIdentityScope(type);

        channelDBBeanDao = new ChannelDBBeanDao(channelDBBeanDaoConfig, this);
        channelDBOne2NDao = new ChannelDBOne2NDao(channelDBOne2NDaoConfig, this);

        registerDao(ChannelDBBean.class, channelDBBeanDao);
        registerDao(ChannelDBOne2N.class, channelDBOne2NDao);
    }
    
    public void clear() {
        channelDBBeanDaoConfig.clearIdentityScope();
        channelDBOne2NDaoConfig.clearIdentityScope();
    }

    public ChannelDBBeanDao getChannelDBBeanDao() {
        return channelDBBeanDao;
    }

    public ChannelDBOne2NDao getChannelDBOne2NDao() {
        return channelDBOne2NDao;
    }

}
