package cent.news.com.newscent.db.graeendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cent.news.com.newscent.news.channel.ChannelDBBean;

import cent.news.com.newscent.db.graeendao.ChannelDBBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig channelDBBeanDaoConfig;

    private final ChannelDBBeanDao channelDBBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        channelDBBeanDaoConfig = daoConfigMap.get(ChannelDBBeanDao.class).clone();
        channelDBBeanDaoConfig.initIdentityScope(type);

        channelDBBeanDao = new ChannelDBBeanDao(channelDBBeanDaoConfig, this);

        registerDao(ChannelDBBean.class, channelDBBeanDao);
    }
    
    public void clear() {
        channelDBBeanDaoConfig.clearIdentityScope();
    }

    public ChannelDBBeanDao getChannelDBBeanDao() {
        return channelDBBeanDao;
    }

}
